// tslint:disable:max-line-length
// tslint:disable:object-literal-key-quotes
export default {
  auth: {
    apiAddress: "https://yv-plans-api-dev.herokuapp.com",
    token:
      "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoxLCJhcGlfa2V5IjoiMzdjYWJhYzQ3Njk3OTQxYmY2OWU4NWFjYTFiZjAxMjE3NDkwZDAxYzYyZjI2MGQ4MTkifX0.QBuFWPrGrtYS52l5S4cqAZnDHOvqZTZZmVzR5sdz6XA",
    error: null,
    test: null,
    user: {
      object: "user",
      id: 1,
      created_at: "2017-02-27T17: 03: 02.425Z",
      updated_at: "2017-06-23T19: 30: 03.225Z",
      status: "active",
      role: "admin",
      first_name: "Mr. Adminasdf",
      last_name: "McPoobear",
      email: "admin@ovenbits.com",
      profile_photo: {
        object: "attachment",
        id: 33,
        created_at: "2017-03-13T20: 53: 31.824Z",
        updated_at: "2017-03-13T20: 53: 34.368Z",
        organization_id: 1,
        status: "processing",
        source_url:
          "https://yv-partner-portal-dev.s3.amazonaws.com/uploads/7a8bafd3-6397-4f49-b17d-f5920330701a/headshot_square_small.png",
        asset: {
          thumb_url:
            "https://yv-partner-portal-dev.s3.amazonaws.com/uploads/7a8bafd3-6397-4f49-b17d-f5920330701a/headshot_square_small.png",
          large_url:
            "https://yv-partner-portal-dev.s3.amazonaws.com/uploads/7a8bafd3-6397-4f49-b17d-f5920330701a/headshot_square_small.png",
          original_url:
            "https://yv-partner-portal-dev.s3.amazonaws.com/uploads/7a8bafd3-6397-4f49-b17d-f5920330701a/headshot_square_small.png",
        },
      },
    },
    isEditingAccount: false,
    isPasswordEditingAccount: false,
    isSavingAccount: false,
  },
  plans: {
    plansById: {},
    planDaysById: {},
    commentsById: {},
    categoriesById: {
      Parents: {
        id: "Parents",
        name: "Parents",
        sections: ["Plans for..."],
      },
      "Young Adults": {
        id: "Young Adults",
        name: "Young Adults",
        sections: ["Plans for..."],
      },
      Women: {
        id: "Women",
        name: "Women",
        sections: ["Plans for..."],
      },
      Men: {
        id: "Men",
        name: "Men",
        sections: ["Plans for..."],
      },
      Youth: {
        id: "Youth",
        name: "Youth",
        sections: ["Plans for..."],
      },
      Kids: {
        id: "Kids",
        name: "Kids",
        sections: ["Plans for..."],
      },
      Families: {
        id: "Families",
        name: "Families",
        sections: ["Plans for..."],
      },
      Groups: {
        id: "Groups",
        name: "Groups",
        sections: ["Plans for..."],
      },
      Singles: {
        id: "Singles",
        name: "Singles",
        sections: ["Plans for..."],
      },
      Audio: {
        id: "Audio",
        name: "Audio",
        sections: ["Listen & Watch"],
      },
      Video: {
        id: "Video",
        name: "Video",
        sections: ["Listen & Watch"],
      },
      "Biblical Study": {
        id: "Biblical Study",
        name: "Biblical Study",
        sections: ["Through the Bible"],
      },
      Whole: {
        id: "Whole",
        name: "Whole",
        sections: ["Through the Bible"],
      },
      Titus: {
        id: "Titus",
        name: "Titus",
        sections: ["Through the Bible"],
      },
      Exodus: {
        id: "Exodus",
        name: "Exodus",
        sections: ["Through the Bible"],
      },
      "2 Peter": {
        id: "2 Peter",
        name: "2 Peter",
        sections: ["Through the Bible"],
      },
      Ephesians: {
        id: "Ephesians",
        name: "Ephesians",
        sections: ["Through the Bible"],
      },
      Joshua: {
        id: "Joshua",
        name: "Joshua",
        sections: ["Through the Bible"],
      },
      Proverbs: {
        id: "Proverbs",
        name: "Proverbs",
        sections: ["Through the Bible"],
      },
      Job: {
        id: "Job",
        name: "Job",
        sections: ["Through the Bible"],
      },
      "3 John": {
        id: "3 John",
        name: "3 John",
        sections: ["Through the Bible"],
      },
      Joel: {
        id: "Joel",
        name: "Joel",
        sections: ["Through the Bible"],
      },
      Revelation: {
        id: "Revelation",
        name: "Revelation",
        sections: ["Through the Bible"],
      },
      James: {
        id: "James",
        name: "James",
        sections: ["Through the Bible"],
      },
      Mark: {
        id: "Mark",
        name: "Mark",
        sections: ["Through the Bible"],
      },
      "2 John": {
        id: "2 John",
        name: "2 John",
        sections: ["Through the Bible"],
      },
      Matthew: {
        id: "Matthew",
        name: "Matthew",
        sections: ["Through the Bible"],
      },
      Philemon: {
        id: "Philemon",
        name: "Philemon",
        sections: ["Through the Bible"],
      },
      "2 Corinthians": {
        id: "2 Corinthians",
        name: "2 Corinthians",
        sections: ["Through the Bible"],
      },
      Philippians: {
        id: "Philippians",
        name: "Philippians",
        sections: ["Through the Bible"],
      },
      Judges: {
        id: "Judges",
        name: "Judges",
        sections: ["Through the Bible"],
      },
      Deuteronomy: {
        id: "Deuteronomy",
        name: "Deuteronomy",
        sections: ["Through the Bible"],
      },
      "1 Thessalonians": {
        id: "1 Thessalonians",
        name: "1 Thessalonians",
        sections: ["Through the Bible"],
      },
      "1 Timothy": {
        id: "1 Timothy",
        name: "1 Timothy",
        sections: ["Through the Bible"],
      },
      Romans: {
        id: "Romans",
        name: "Romans",
        sections: ["Through the Bible"],
      },
      Genesis: {
        id: "Genesis",
        name: "Genesis",
        sections: ["Through the Bible"],
      },
      Psalm: {
        id: "Psalm",
        name: "Psalm",
        sections: ["Through the Bible"],
      },
      Nehemiah: {
        id: "Nehemiah",
        name: "Nehemiah",
        sections: ["Through the Bible"],
      },
      "2 Timothy": {
        id: "2 Timothy",
        name: "2 Timothy",
        sections: ["Through the Bible"],
      },
      Acts: {
        id: "Acts",
        name: "Acts",
        sections: ["Through the Bible"],
      },
      Isaiah: {
        id: "Isaiah",
        name: "Isaiah",
        sections: ["Through the Bible"],
      },
      Luke: {
        id: "Luke",
        name: "Luke",
        sections: ["Through the Bible"],
      },
      Colossians: {
        id: "Colossians",
        name: "Colossians",
        sections: ["Through the Bible"],
      },
      Ecclesiastes: {
        id: "Ecclesiastes",
        name: "Ecclesiastes",
        sections: ["Through the Bible"],
      },
      Numbers: {
        id: "Numbers",
        name: "Numbers",
        sections: ["Through the Bible"],
      },
      "1 Samuel": {
        id: "1 Samuel",
        name: "1 Samuel",
        sections: ["Through the Bible"],
      },
      Hebrews: {
        id: "Hebrews",
        name: "Hebrews",
        sections: ["Through the Bible"],
      },
      John: {
        id: "John",
        name: "John",
        sections: ["Through the Bible"],
      },
      Leviticus: {
        id: "Leviticus",
        name: "Leviticus",
        sections: ["Through the Bible"],
      },
      "1 Chronicles": {
        id: "1 Chronicles",
        name: "1 Chronicles",
        sections: ["Through the Bible"],
      },
      "1 Corinthians": {
        id: "1 Corinthians",
        name: "1 Corinthians",
        sections: ["Through the Bible"],
      },
      Ruth: {
        id: "Ruth",
        name: "Ruth",
        sections: ["Through the Bible"],
      },
      "1 Peter": {
        id: "1 Peter",
        name: "1 Peter",
        sections: ["Through the Bible"],
      },
      Daniel: {
        id: "Daniel",
        name: "Daniel",
        sections: ["Through the Bible"],
      },
      Galatians: {
        id: "Galatians",
        name: "Galatians",
        sections: ["Through the Bible"],
      },
      Esther: {
        id: "Esther",
        name: "Esther",
        sections: ["Through the Bible"],
      },
      "1 John": {
        id: "1 John",
        name: "1 John",
        sections: ["Through the Bible"],
      },
      "2 Samuel": {
        id: "2 Samuel",
        name: "2 Samuel",
        sections: ["Through the Bible"],
      },
      Jude: {
        id: "Jude",
        name: "Jude",
        sections: ["Through the Bible"],
      },
      Ezra: {
        id: "Ezra",
        name: "Ezra",
        sections: ["Through the Bible"],
      },
      Marriage: {
        id: "Marriage",
        name: "Marriage",
        sections: ["Relationships"],
      },
      Dating: {
        id: "Dating",
        name: "Dating",
        sections: ["Relationships"],
      },
      Divorce: {
        id: "Divorce",
        name: "Divorce",
        sections: ["Relationships"],
      },
      Sex: {
        id: "Sex",
        name: "Sex",
        sections: ["Relationships"],
      },
      Loss: {
        id: "Loss",
        name: "Loss",
        sections: ["Feelings"],
      },
      Hope: {
        id: "Hope",
        name: "Hope",
        sections: ["Feelings"],
      },
      Jealousy: {
        id: "Jealousy",
        name: "Jealousy",
        sections: ["Feelings"],
      },
      Temptation: {
        id: "Temptation",
        name: "Temptation",
        sections: ["Feelings"],
      },
      Pride: {
        id: "Pride",
        name: "Pride",
        sections: ["Feelings"],
      },
      Peace: {
        id: "Peace",
        name: "Peace",
        sections: ["Feelings"],
      },
      Patience: {
        id: "Patience",
        name: "Patience",
        sections: ["Feelings"],
      },
      Depression: {
        id: "Depression",
        name: "Depression",
        sections: ["Feelings"],
      },
      Love: {
        id: "Love",
        name: "Love",
        sections: ["Feelings"],
      },
      Doubt: {
        id: "Doubt",
        name: "Doubt",
        sections: ["Feelings"],
      },
      Anxiety: {
        id: "Anxiety",
        name: "Anxiety",
        sections: ["Feelings"],
      },
      Healing: {
        id: "Healing",
        name: "Healing",
        sections: ["Feelings"],
      },
      Anger: {
        id: "Anger",
        name: "Anger",
        sections: ["Feelings"],
      },
      Fear: {
        id: "Fear",
        name: "Fear",
        sections: ["Feelings"],
      },
      Stress: {
        id: "Stress",
        name: "Stress",
        sections: ["Feelings"],
      },
      Joy: {
        id: "Joy",
        name: "Joy",
        sections: ["Feelings"],
      },
      Authors: {
        id: "Authors",
        name: "Authors",
        sections: ["You may know..."],
      },
      Musicians: {
        id: "Musicians",
        name: "Musicians",
        sections: ["You may know..."],
      },
      Athletes: {
        id: "Athletes",
        name: "Athletes",
        sections: ["You may know..."],
      },
      Fasting: {
        id: "Fasting",
        name: "Fasting",
        sections: ["Popular Topics"],
      },
      Leadership: {
        id: "Leadership",
        name: "Leadership",
        sections: ["Popular Topics"],
      },
      Work: {
        id: "Work",
        name: "Work",
        sections: ["Popular Topics"],
      },
      Forgiveness: {
        id: "Forgiveness",
        name: "Forgiveness",
        sections: ["Popular Topics"],
      },
      Trust: {
        id: "Trust",
        name: "Trust",
        sections: ["Popular Topics"],
      },
      Addiction: {
        id: "Addiction",
        name: "Addiction",
        sections: ["Popular Topics"],
      },
      "New to Faith": {
        id: "New to Faith",
        name: "New to Faith",
        sections: ["Popular Topics"],
      },
      Health: {
        id: "Health",
        name: "Health",
        sections: ["Popular Topics"],
      },
      Finances: {
        id: "Finances",
        name: "Finances",
        sections: ["Popular Topics"],
      },
      Missions: {
        id: "Missions",
        name: "Missions",
        sections: ["Popular Topics"],
      },
      Purpose: {
        id: "Purpose",
        name: "Purpose",
        sections: ["Popular Topics"],
      },
      Worship: {
        id: "Worship",
        name: "Worship",
        sections: ["Popular Topics"],
      },
      "Lent/Easter": {
        id: "Lent/Easter",
        name: "Lent/Easter",
        sections: ["Popular Topics"],
      },
      Christmas: {
        id: "Christmas",
        name: "Christmas",
        sections: ["Popular Topics"],
      },
      Advent: {
        id: "Advent",
        name: "Advent",
        sections: ["Popular Topics"],
      },
      Grace: {
        id: "Grace",
        name: "Grace",
        sections: ["Popular Topics"],
      },
      Humility: {
        id: "Humility",
        name: "Humility",
        sections: ["Popular Topics"],
      },
      "Christian Living": {
        id: "Christian Living",
        name: "Christian Living",
        sections: ["Popular Topics"],
      },
      Encouragement: {
        id: "Encouragement",
        name: "Encouragement",
        sections: ["Popular Topics"],
      },
      Suffering: {
        id: "Suffering",
        name: "Suffering",
        sections: ["Popular Topics"],
      },
      Wisdom: {
        id: "Wisdom",
        name: "Wisdom",
        sections: ["Popular Topics"],
      },
      Faith: {
        id: "Faith",
        name: "Faith",
        sections: ["Popular Topics"],
      },
      Prayer: {
        id: "Prayer",
        name: "Prayer",
        sections: ["Popular Topics"],
      },
    },
    planRevisionsById: {},
    allCategoryIds: [
      "Parents",
      "Young Adults",
      "Women",
      "Men",
      "Youth",
      "Kids",
      "Families",
      "Groups",
      "Singles",
      "Audio",
      "Video",
      "Biblical Study",
      "Whole",
      "Titus",
      "Exodus",
      "2 Peter",
      "Ephesians",
      "Joshua",
      "Proverbs",
      "Job",
      "3 John",
      "Joel",
      "Revelation",
      "James",
      "Mark",
      "2 John",
      "Matthew",
      "Philemon",
      "2 Corinthians",
      "Philippians",
      "Judges",
      "Deuteronomy",
      "1 Thessalonians",
      "1 Timothy",
      "Romans",
      "Genesis",
      "Psalm",
      "Nehemiah",
      "2 Timothy",
      "Acts",
      "Isaiah",
      "Luke",
      "Colossians",
      "Ecclesiastes",
      "Numbers",
      "1 Samuel",
      "Hebrews",
      "John",
      "Leviticus",
      "1 Chronicles",
      "1 Corinthians",
      "Ruth",
      "1 Peter",
      "Daniel",
      "Galatians",
      "Esther",
      "1 John",
      "2 Samuel",
      "Jude",
      "Ezra",
      "Marriage",
      "Dating",
      "Divorce",
      "Sex",
      "Loss",
      "Hope",
      "Jealousy",
      "Temptation",
      "Pride",
      "Peace",
      "Patience",
      "Depression",
      "Love",
      "Doubt",
      "Anxiety",
      "Healing",
      "Anger",
      "Fear",
      "Stress",
      "Joy",
      "Authors",
      "Musicians",
      "Athletes",
      "Fasting",
      "Leadership",
      "Work",
      "Forgiveness",
      "Trust",
      "Addiction",
      "New to Faith",
      "Health",
      "Finances",
      "Missions",
      "Purpose",
      "Worship",
      "Lent/Easter",
      "Christmas",
      "Advent",
      "Grace",
      "Humility",
      "Christian Living",
      "Encouragement",
      "Suffering",
      "Wisdom",
      "Faith",
      "Prayer",
    ],
    categorySections: [
      "Plans for...",
      "Listen & Watch",
      "Through the Bible",
      "Relationships",
      "Feelings",
      "You may know...",
      "Popular Topics",
    ],
    allPlanIds: [],
    allPlanRevisionIds: [],
    planDayIdsByPlanId: {},
    planCommentIdsByPlanId: {},
    dayCommentIdsByDayId: {},
    isLoadingPlans: false,
    isLoadingPlan: true,
    isLoadingSubmission: false,
    activePlanId: null,
    plansPagination: null,
    plansSorter: {
      sort: null,
      order: "desc",
    },
    languages: [
      {
        object: "language",
        id: 1,
        created_at: "2017-03-06T18: 39: 04.955Z",
        updated_at: "2017-03-06T18: 39: 04.955Z",
        code: "en",
        name: "English",
        position: 0,
      },
      {
        object: "language",
        id: 2,
        created_at: "2017-03-06T18: 39: 04.974Z",
        updated_at: "2017-03-06T18: 39: 04.974Z",
        code: "af",
        name: "Afrikaans",
        position: null,
      },
      {
        object: "language",
        id: 39,
        created_at: "2017-03-06T18: 39: 05.580Z",
        updated_at: "2017-03-06T18: 39: 05.580Z",
        code: "sq",
        name: "Albanian",
        position: null,
      },
      {
        object: "language",
        id: 3,
        created_at: "2017-03-06T18: 39: 04.989Z",
        updated_at: "2017-03-06T18: 39: 04.989Z",
        code: "ar",
        name: "Arabic",
        position: null,
      },
      {
        object: "language",
        id: 4,
        created_at: "2017-03-06T18: 39: 05.007Z",
        updated_at: "2017-03-06T18: 39: 05.007Z",
        code: "be",
        name: "Belarusian",
        position: null,
      },
      {
        object: "language",
        id: 5,
        created_at: "2017-03-06T18: 39: 05.034Z",
        updated_at: "2017-03-06T18: 39: 05.034Z",
        code: "bg",
        name: "Bulgarian",
        position: null,
      },
      {
        object: "language",
        id: 29,
        created_at: "2017-03-06T18: 39: 05.410Z",
        updated_at: "2017-03-06T18: 39: 05.410Z",
        code: "my",
        name: "Burmese",
        position: null,
      },
      {
        object: "language",
        id: 6,
        created_at: "2017-03-06T18: 39: 05.059Z",
        updated_at: "2017-03-06T18: 39: 05.059Z",
        code: "ca",
        name: "Catalan",
        position: null,
      },
      {
        object: "language",
        id: 49,
        created_at: "2017-03-06T18: 39: 05.695Z",
        updated_at: "2017-03-06T18: 39: 05.695Z",
        code: "zh_CN",
        name: "Chinese Simplified",
        position: null,
      },
      {
        object: "language",
        id: 50,
        created_at: "2017-03-06T18: 39: 05.705Z",
        updated_at: "2017-03-06T18: 39: 05.705Z",
        code: "zh_TW",
        name: "Chinese Traditional",
        position: null,
      },
      {
        object: "language",
        id: 18,
        created_at: "2017-03-06T18: 39: 05.259Z",
        updated_at: "2017-03-06T18: 39: 05.259Z",
        code: "hr",
        name: "Croatian",
        position: null,
      },
      {
        object: "language",
        id: 7,
        created_at: "2017-03-06T18: 39: 05.075Z",
        updated_at: "2017-03-06T18: 39: 05.075Z",
        code: "cs",
        name: "Czech",
        position: null,
      },
      {
        object: "language",
        id: 9,
        created_at: "2017-03-06T18: 39: 05.117Z",
        updated_at: "2017-03-06T18: 39: 05.117Z",
        code: "da",
        name: "Danish",
        position: null,
      },
      {
        object: "language",
        id: 30,
        created_at: "2017-03-06T18: 39: 05.424Z",
        updated_at: "2017-03-06T18: 39: 05.424Z",
        code: "nl",
        name: "Dutch",
        position: null,
      },
      {
        object: "language",
        id: 14,
        created_at: "2017-03-06T18: 39: 05.197Z",
        updated_at: "2017-03-06T18: 39: 05.197Z",
        code: "fa",
        name: "Farsi",
        position: null,
      },
      {
        object: "language",
        id: 44,
        created_at: "2017-03-06T18: 39: 05.639Z",
        updated_at: "2017-03-06T18: 39: 05.639Z",
        code: "tl",
        name: "Filipino",
        position: null,
      },
      {
        object: "language",
        id: 15,
        created_at: "2017-03-06T18: 39: 05.216Z",
        updated_at: "2017-03-06T18: 39: 05.216Z",
        code: "fi",
        name: "Finnish",
        position: null,
      },
      {
        object: "language",
        id: 16,
        created_at: "2017-03-06T18: 39: 05.227Z",
        updated_at: "2017-03-06T18: 39: 05.227Z",
        code: "fr",
        name: "French",
        position: null,
      },
      {
        object: "language",
        id: 10,
        created_at: "2017-03-06T18: 39: 05.130Z",
        updated_at: "2017-03-06T18: 39: 05.130Z",
        code: "de",
        name: "German",
        position: null,
      },
      {
        object: "language",
        id: 11,
        created_at: "2017-03-06T18: 39: 05.150Z",
        updated_at: "2017-03-06T18: 39: 05.150Z",
        code: "el",
        name: "Greek",
        position: null,
      },
      {
        object: "language",
        id: 17,
        created_at: "2017-03-06T18: 39: 05.247Z",
        updated_at: "2017-03-06T18: 39: 05.247Z",
        code: "hi",
        name: "Hindi",
        position: null,
      },
      {
        object: "language",
        id: 19,
        created_at: "2017-03-06T18: 39: 05.274Z",
        updated_at: "2017-03-06T18: 39: 05.274Z",
        code: "hu",
        name: "Hungarian",
        position: null,
      },
      {
        object: "language",
        id: 20,
        created_at: "2017-03-06T18: 39: 05.289Z",
        updated_at: "2017-03-06T18: 39: 05.289Z",
        code: "id",
        name: "Indonesian",
        position: null,
      },
      {
        object: "language",
        id: 21,
        created_at: "2017-03-06T18: 39: 05.306Z",
        updated_at: "2017-03-06T18: 39: 05.306Z",
        code: "it",
        name: "Italian",
        position: null,
      },
      {
        object: "language",
        id: 22,
        created_at: "2017-03-06T18: 39: 05.323Z",
        updated_at: "2017-03-06T18: 39: 05.323Z",
        code: "ja",
        name: "Japanese",
        position: null,
      },
      {
        object: "language",
        id: 23,
        created_at: "2017-03-06T18: 39: 05.336Z",
        updated_at: "2017-03-06T18: 39: 05.336Z",
        code: "km",
        name: "Khmer",
        position: null,
      },
      {
        object: "language",
        id: 24,
        created_at: "2017-03-06T18: 39: 05.347Z",
        updated_at: "2017-03-06T18: 39: 05.347Z",
        code: "ko",
        name: "Korean",
        position: null,
      },
      {
        object: "language",
        id: 25,
        created_at: "2017-03-06T18: 39: 05.358Z",
        updated_at: "2017-03-06T18: 39: 05.358Z",
        code: "lv",
        name: "Latvian",
        position: null,
      },
      {
        object: "language",
        id: 26,
        created_at: "2017-03-06T18: 39: 05.370Z",
        updated_at: "2017-03-06T18: 39: 05.370Z",
        code: "mk",
        name: "Macedonian",
        position: null,
      },
      {
        object: "language",
        id: 28,
        created_at: "2017-03-06T18: 39: 05.399Z",
        updated_at: "2017-03-06T18: 39: 05.399Z",
        code: "ms",
        name: "Malay",
        position: null,
      },
      {
        object: "language",
        id: 27,
        created_at: "2017-03-06T18: 39: 05.381Z",
        updated_at: "2017-03-06T18: 39: 05.381Z",
        code: "mn",
        name: "Mongolian",
        position: null,
      },
      {
        object: "language",
        id: 31,
        created_at: "2017-03-06T18: 39: 05.436Z",
        updated_at: "2017-03-06T18: 39: 05.436Z",
        code: "no",
        name: "Norwegian",
        position: null,
      },
      {
        object: "language",
        id: 32,
        created_at: "2017-03-06T18: 39: 05.474Z",
        updated_at: "2017-03-06T18: 39: 05.474Z",
        code: "pl",
        name: "Polish",
        position: null,
      },
      {
        object: "language",
        id: 33,
        created_at: "2017-03-06T18: 39: 05.489Z",
        updated_at: "2017-03-06T18: 39: 05.489Z",
        code: "pt",
        name: "Portuguese (BR)",
        position: null,
      },
      {
        object: "language",
        id: 34,
        created_at: "2017-03-06T18: 39: 05.511Z",
        updated_at: "2017-03-06T18: 39: 05.511Z",
        code: "pt_PT",
        name: "Portuguese (PT)",
        position: null,
      },
      {
        object: "language",
        id: 35,
        created_at: "2017-03-06T18: 39: 05.523Z",
        updated_at: "2017-03-06T18: 39: 05.523Z",
        code: "ro",
        name: "Romanian",
        position: null,
      },
      {
        object: "language",
        id: 36,
        created_at: "2017-03-06T18: 39: 05.546Z",
        updated_at: "2017-03-06T18: 39: 05.546Z",
        code: "ru",
        name: "Russian",
        position: null,
      },
      {
        object: "language",
        id: 38,
        created_at: "2017-03-06T18: 39: 05.569Z",
        updated_at: "2017-03-06T18: 39: 05.569Z",
        code: "sn",
        name: "Shona",
        position: null,
      },
      {
        object: "language",
        id: 37,
        created_at: "2017-03-06T18: 39: 05.558Z",
        updated_at: "2017-03-06T18: 39: 05.558Z",
        code: "sk",
        name: "Slovak",
        position: null,
      },
      {
        object: "language",
        id: 12,
        created_at: "2017-03-06T18: 39: 05.164Z",
        updated_at: "2017-03-06T18: 39: 05.164Z",
        code: "es",
        name: "Spanish (MX)",
        position: null,
      },
      {
        object: "language",
        id: 13,
        created_at: "2017-03-06T18: 39: 05.186Z",
        updated_at: "2017-03-06T18: 39: 05.186Z",
        code: "es_ES",
        name: "Spanish (Spain)",
        position: null,
      },
      {
        object: "language",
        id: 41,
        created_at: "2017-03-06T18: 39: 05.601Z",
        updated_at: "2017-03-06T18: 39: 05.601Z",
        code: "sw",
        name: "Swahili",
        position: null,
      },
      {
        object: "language",
        id: 40,
        created_at: "2017-03-06T18: 39: 05.591Z",
        updated_at: "2017-03-06T18: 39: 05.591Z",
        code: "sv",
        name: "Swedish",
        position: null,
      },
      {
        object: "language",
        id: 42,
        created_at: "2017-03-06T18: 39: 05.620Z",
        updated_at: "2017-03-06T18: 39: 05.620Z",
        code: "ta",
        name: "Tamil",
        position: null,
      },
      {
        object: "language",
        id: 43,
        created_at: "2017-03-06T18: 39: 05.630Z",
        updated_at: "2017-03-06T18: 39: 05.630Z",
        code: "th",
        name: "Thai",
        position: null,
      },
      {
        object: "language",
        id: 45,
        created_at: "2017-03-06T18: 39: 05.651Z",
        updated_at: "2017-03-06T18: 39: 05.651Z",
        code: "tr",
        name: "Turkish",
        position: null,
      },
      {
        object: "language",
        id: 46,
        created_at: "2017-03-06T18: 39: 05.664Z",
        updated_at: "2017-03-06T18: 39: 05.664Z",
        code: "uk",
        name: "Ukranian",
        position: null,
      },
      {
        object: "language",
        id: 47,
        created_at: "2017-03-06T18: 39: 05.675Z",
        updated_at: "2017-03-06T18: 39: 05.675Z",
        code: "ur",
        name: "Urdu",
        position: null,
      },
      {
        object: "language",
        id: 48,
        created_at: "2017-03-06T18: 39: 05.686Z",
        updated_at: "2017-03-06T18: 39: 05.686Z",
        code: "vi",
        name: "Vietnamese",
        position: null,
      },
      {
        object: "language",
        id: 8,
        created_at: "2017-03-06T18: 39: 05.105Z",
        updated_at: "2017-03-06T18: 39: 05.105Z",
        code: "cy",
        name: "Welsh",
        position: null,
      },
    ],
  },
  organizations: {
    preferredOrgId: "ALL_ORGS",
    orgsById: {
      1: {
        object: "organization",
        id: 1,
        created_at: "2017-03-05T04: 33: 52.069Z",
        updated_at: "2017-05-22T06: 32: 53.058Z",
        status: "approved",
        name: "Oven Bits",
        information_html:
          "<p>A software design and development agency based in Texas.</p>",
        information_json: {},
        website: "http: //ovenbits.com",
        address: "123 Simpson St",
        phone: "1234567890",
        memberships_count: 8,
        analytics_id: 672,
        role: "admin",
        profile_photo: {
          object: "attachment",
          id: 279,
          created_at: "2017-05-22T06: 32: 51.026Z",
          updated_at: "2017-05-22T06: 32: 54.128Z",
          organization_id: 1,
          status: "processed",
          source_url:
            "https://yv-partner-portal-dev.s3.amazonaws.com/uploads/eeb16f06-7358-48ba-a141-376e08e4969c/topPlansSymbol.png",
          asset: {
            thumb_url:
              "https://s3.amazonaws.com/yv-partner-portal-dev/attachments/assets/000/000/279/thumb/topPlansSymbol.png?1495434773",
            large_url:
              "https://s3.amazonaws.com/yv-partner-portal-dev/attachments/assets/000/000/279/large/topPlansSymbol.png?1495434773",
            original_url:
              "https://s3.amazonaws.com/yv-partner-portal-dev/attachments/assets/000/000/279/original/topPlansSymbol.png?1495434773",
          },
        },
        partnership_agreement: {
          object: "attachment",
          id: 148,
          created_at: "2017-04-07T04: 56: 46.995Z",
          updated_at: "2017-04-07T04: 57: 08.342Z",
          organization_id: 1,
          status: "processed",
          source_url:
            "https://yv-partner-portal-dev.s3.amazonaws.com/uploads/c8b9596f-c528-419a-a0d1-f13f4f512f30/sample.pdf",
          asset: {
            original_url:
              "https://s3.amazonaws.com/yv-partner-portal-dev/attachments/assets/000/000/148/original/sample.pdf?1491541028",
          },
        },
      },
      2: {
        object: "organization",
        id: 2,
        created_at: "2017-03-05T04: 33: 52.107Z",
        updated_at: "2017-04-20T17: 30: 23.898Z",
        status: "approved",
        name: "YouVersion",
        information_html: "<p>Creators of the Bible App</p>",
        information_json: {},
        website: "http: //youversion.com",
        address: "Oklahoma City, OK",
        phone: "1234567890",
        memberships_count: null,
        analytics_id: 3,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      3: {
        object: "organization",
        id: 3,
        created_at: "2017-03-15T17: 33: 14.911Z",
        updated_at: "2017-05-14T06: 04: 35.668Z",
        status: "approved",
        name: "New Orgblorg",
        information_html: null,
        information_json: {},
        website: "www.flooogle.com/?yay",
        address: "123 Floogle St",
        phone: "123.665.2233",
        memberships_count: 1,
        analytics_id: 8,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      4: {
        object: "organization",
        id: 4,
        created_at: "2017-03-15T17: 40: 13.553Z",
        updated_at: "2017-04-20T17: 30: 25.135Z",
        status: "approved",
        name: "Simas Empire",
        information_html: null,
        information_json: {},
        website: "www.ovenbits.com",
        address: "109 Valley View Dr N.",
        phone: "9167160109",
        memberships_count: 2,
        analytics_id: 7,
        role: "admin",
        profile_photo: null,
        partnership_agreement: {
          object: "attachment",
          id: 47,
          created_at: "2017-03-15T19: 32: 23.582Z",
          updated_at: "2017-03-15T19: 32: 24.960Z",
          organization_id: 4,
          status: "processing",
          source_url:
            "https://yv-partner-portal-dev.s3.amazonaws.com/uploads/437e0c6e-b99b-4a4c-af0a-628681eed8d1/2017+Summer+Internship+Program+with+NBCF+-+Application.pdf",
          asset: {
            original_url:
              "https://yv-partner-portal-dev.s3.amazonaws.com/uploads/437e0c6e-b99b-4a4c-af0a-628681eed8d1/2017+Summer+Internship+Program+with+NBCF+-+Application.pdf",
          },
        },
      },
      5: {
        object: "organization",
        id: 5,
        created_at: "2017-03-21T17: 50: 19.772Z",
        updated_at: "2017-04-20T17: 34: 38.820Z",
        status: "approved",
        name: "Blank New Org",
        information_html: null,
        information_json: {},
        website: "Org Numbah5",
        address: "This is Org5!",
        phone: "123555 ORG5",
        memberships_count: 2,
        analytics_id: 19,
        role: "admin",
        profile_photo: {
          object: "attachment",
          id: 138,
          created_at: "2017-04-06T08: 17: 00.012Z",
          updated_at: "2017-04-06T08: 17: 15.598Z",
          organization_id: 5,
          status: "processed",
          source_url:
            "https://yv-partner-portal-dev.s3.amazonaws.com/uploads/ba606312-a5a7-4763-b965-7584cd9d8b81/12640317_10156436418430612_5205911284315347660_o.jpg",
          asset: {
            thumb_url:
              "https://s3.amazonaws.com/yv-partner-portal-dev/attachments/assets/000/000/138/thumb/12640317_10156436418430612_5205911284315347660_o.jpg?1491466635",
            large_url:
              "https://s3.amazonaws.com/yv-partner-portal-dev/attachments/assets/000/000/138/large/12640317_10156436418430612_5205911284315347660_o.jpg?1491466635",
            original_url:
              "https://s3.amazonaws.com/yv-partner-portal-dev/attachments/assets/000/000/138/original/12640317_10156436418430612_5205911284315347660_o.jpg?1491466635",
          },
        },
        partnership_agreement: {
          object: "attachment",
          id: 139,
          created_at: "2017-04-06T08: 17: 07.807Z",
          updated_at: "2017-04-06T08: 17: 14.861Z",
          organization_id: 5,
          status: "processing",
          source_url:
            "https://yv-partner-portal-dev.s3.amazonaws.com/uploads/9483dd6a-10a9-437f-a562-7f95dcaa02b4/nomnom.js",
          asset: {
            original_url:
              "https://yv-partner-portal-dev.s3.amazonaws.com/uploads/9483dd6a-10a9-437f-a562-7f95dcaa02b4/nomnom.js",
          },
        },
      },
      6: {
        object: "organization",
        id: 6,
        created_at: "2017-03-25T20: 44: 22.359Z",
        updated_at: "2017-04-20T17: 30: 26.043Z",
        status: "approved",
        name: "Yippie Testing Password Org",
        information_html: null,
        information_json: {},
        website: "123.com",
        address: "asdfasdf",
        phone: "123123123123",
        memberships_count: 1,
        analytics_id: 10,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      7: {
        object: "organization",
        id: 7,
        created_at: "2017-03-25T20: 45: 42.837Z",
        updated_at: "2017-04-20T17: 30: 25.747Z",
        status: "approved",
        name: "Whoops forgot",
        information_html: null,
        information_json: {},
        website: "asdf",
        address: "asdf",
        phone: "asdf",
        memberships_count: 1,
        analytics_id: 9,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      8: {
        object: "organization",
        id: 8,
        created_at: "2017-03-25T20: 47: 46.174Z",
        updated_at: "2017-04-20T17: 34: 37.476Z",
        status: "approved",
        name: "BLAH",
        information_html: null,
        information_json: {},
        website: "BLAH",
        address: "blah",
        phone: "blah",
        memberships_count: 1,
        analytics_id: 15,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      9: {
        object: "organization",
        id: 9,
        created_at: "2017-04-06T05: 51: 46.011Z",
        updated_at: "2017-04-20T17: 34: 37.803Z",
        status: "approved",
        name: "World Org.",
        information_html: null,
        information_json: {},
        website: "www.bigtime.com",
        address: "123 Wee",
        phone: "123123123",
        memberships_count: 1,
        analytics_id: 16,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      10: {
        object: "organization",
        id: 10,
        created_at: "2017-04-06T06: 27: 58.108Z",
        updated_at: "2017-04-20T17: 34: 37.173Z",
        status: "approved",
        name: "NewOrg Apr.5",
        information_html: null,
        information_json: {},
        website: "www.goog.e.cl.e.com",
        address: "123 Google",
        phone: "123xx3",
        memberships_count: 1,
        analytics_id: 14,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      11: {
        object: "organization",
        id: 11,
        created_at: "2017-04-06T07: 06: 06.737Z",
        updated_at: "2017-04-20T17: 34: 38.479Z",
        status: "approved",
        name: "No Whammies",
        information_html: null,
        information_json: {},
        website: "Nowhmammahwhwo",
        address: "444 NO",
        phone: "11233",
        memberships_count: 1,
        analytics_id: 18,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      12: {
        object: "organization",
        id: 12,
        created_at: "2017-04-06T08: 57: 28.304Z",
        updated_at: "2017-04-20T17: 34: 39.156Z",
        status: "approved",
        name: "Another Fun Org",
        information_html: null,
        information_json: {},
        website: "asdfas",
        address: "asdfa",
        phone: "asdf",
        memberships_count: 1,
        analytics_id: 20,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      13: {
        object: "organization",
        id: 13,
        created_at: "2017-04-06T09: 03: 15.315Z",
        updated_at: "2017-04-20T17: 34: 39.502Z",
        status: "approved",
        name: "YIPYIP",
        information_html: null,
        information_json: {},
        website: "asdf",
        address: "asf",
        phone: "asdf",
        memberships_count: 1,
        analytics_id: 21,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      14: {
        object: "organization",
        id: 14,
        created_at: "2017-04-06T09: 17: 46.862Z",
        updated_at: "2017-04-20T17: 34: 39.834Z",
        status: "approved",
        name: "Fondu Org",
        information_html: null,
        information_json: {},
        website: "asdf",
        address: "asdf",
        phone: "asdf",
        memberships_count: 2,
        analytics_id: 22,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      15: {
        object: "organization",
        id: 15,
        created_at: "2017-04-07T19: 54: 36.499Z",
        updated_at: "2017-04-20T17: 30: 24.202Z",
        status: "approved",
        name: "FireFox Test",
        information_html: null,
        information_json: {},
        website: "www.google.com",
        address: "123",
        phone: "123",
        memberships_count: 2,
        analytics_id: 4,
        role: "admin",
        profile_photo: {
          object: "attachment",
          id: 151,
          created_at: "2017-04-07T20: 05: 03.132Z",
          updated_at: "2017-04-07T20: 05: 30.017Z",
          organization_id: 15,
          status: "processed",
          source_url:
            "https://yv-partner-portal-dev.s3.amazonaws.com/uploads/a94987e4-1970-4ec2-916a-b506ecdf647e/2014-10-01.jpg",
          asset: {
            thumb_url:
              "https://s3.amazonaws.com/yv-partner-portal-dev/attachments/assets/000/000/151/thumb/2014-10-01.jpg?1491595529",
            large_url:
              "https://s3.amazonaws.com/yv-partner-portal-dev/attachments/assets/000/000/151/large/2014-10-01.jpg?1491595529",
            original_url:
              "https://s3.amazonaws.com/yv-partner-portal-dev/attachments/assets/000/000/151/original/2014-10-01.jpg?1491595529",
          },
        },
        partnership_agreement: {
          object: "attachment",
          id: 152,
          created_at: "2017-04-07T20: 05: 16.432Z",
          updated_at: "2017-04-07T20: 05: 57.251Z",
          organization_id: 15,
          status: "processed",
          source_url:
            "https://yv-partner-portal-dev.s3.amazonaws.com/uploads/8cb4e43e-2041-43e3-b8d7-9e4dedbe89d8/p0fo-_fo.png",
          asset: {
            original_url:
              "https://s3.amazonaws.com/yv-partner-portal-dev/attachments/assets/000/000/152/original/p0fo-_fo.png?1491595557",
          },
        },
      },
      16: {
        object: "organization",
        id: 16,
        created_at: "2017-04-07T20: 44: 22.155Z",
        updated_at: "2017-04-20T17: 30: 24.512Z",
        status: "approved",
        name: "AltOrg Test",
        information_html: null,
        information_json: {},
        website: "Test",
        address: "tst",
        phone: "test",
        memberships_count: 2,
        analytics_id: 5,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      18: {
        object: "organization",
        id: 18,
        created_at: "2017-04-11T22: 42: 03.064Z",
        updated_at: "2017-04-22T13: 18: 41.936Z",
        status: "approved",
        name: "Court Co",
        information_html: null,
        information_json: {},
        website: "courtsimas.com",
        address: "2211 North Lamar St, #302",
        phone: "9167160109",
        memberships_count: 2,
        analytics_id: null,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      19: {
        object: "organization",
        id: 19,
        created_at: "2017-04-17T21: 25: 25.343Z",
        updated_at: "2017-04-20T17: 34: 38.150Z",
        status: "approved",
        name: "Developer Access",
        information_html: null,
        information_json: {},
        website: "http: //www.ovenbits.com",
        address: "nil nil",
        phone: "9167160109",
        memberships_count: 1,
        analytics_id: 17,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      20: {
        object: "organization",
        id: 20,
        created_at: "2017-04-20T17: 51: 09.749Z",
        updated_at: "2017-04-20T17: 51: 09.749Z",
        status: "approved",
        name: "TEST PARTNER TWO",
        information_html: null,
        information_json: {},
        website: "n/a",
        address: "n/a",
        phone: "000-000-0000",
        memberships_count: null,
        analytics_id: 2,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      21: {
        object: "organization",
        id: 21,
        created_at: "2017-04-20T17: 51: 10.103Z",
        updated_at: "2017-04-20T17: 51: 10.103Z",
        status: "approved",
        name: "TEST PARTNER",
        information_html: null,
        information_json: {},
        website: "n/a",
        address: "n/a",
        phone: "000-000-0000",
        memberships_count: null,
        analytics_id: 1,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
      22: {
        object: "organization",
        id: 22,
        created_at: "2017-05-21T23: 32: 01.096Z",
        updated_at: "2017-05-21T23: 32: 01.096Z",
        status: "approved",
        name: "Hey Test Approve/Reject",
        information_html: null,
        information_json: {},
        website: "asf",
        address: "sadf",
        phone: "asdf",
        memberships_count: 1,
        analytics_id: null,
        role: "admin",
        profile_photo: null,
        partnership_agreement: null,
      },
    },
    usersById: {},
    curentPageOrgIds: [
      3,
      2,
      15,
      16,
      4,
      7,
      6,
      10,
      8,
      9,
      19,
      11,
      5,
      12,
      13,
      14,
      20,
      21,
      18,
      22,
      1,
    ],
    activeOrgUserIds: [],
    activeOrgId: 1,
    loading: false,
    isEditingOrg: false,
    showOrgModal: false,
    isLoadingUsers: false,
    viewingAllOrganizations: true,
    orgsPagination: {
      currentPage: 1,
      nextPage: null,
      prevPage: null,
      totalPages: 1,
      totalCount: 21,
    },
    orgsSorter: {
      sort: null,
      order: "desc",
    },
    userLoadError: false,
    isSavingUser: false,
    isEditingUser: false,
    isPasswordEditingUser: false,
    usersPagination: null,
    usersSorter: {
      sort: null,
      order: "desc",
    },
    analyticsAuth: {
      username: "partner-portal",
      password: "6d67c237075e493bc523cb6dabd48dd42c7982ce",
    },
    analyticsDataByKey: {
      "plan-activity-by-year": {
        isLoading: true,
        failedLoad: false,
        resultset: null,
        year: 2017,
      },
      "top-plans-completions": {
        isLoading: true,
        failedLoad: false,
        resultset: null,
      },
      "historical-completions": {
        isLoading: true,
        failedLoad: false,
        resultset: null,
      },
      "per-day-completion-rate": {
        isLoading: true,
        failedLoad: false,
        resultset: null,
      },
      "per-day-subscription-rate": {
        isLoading: true,
        failedLoad: false,
        resultset: null,
      },
      "rp-sub-yoy": {
        isLoading: true,
        failedLoad: false,
        resultset: null,
      },
      "top-plans-subscribers": {
        isLoading: true,
        failedLoad: false,
        resultset: null,
      },
      "completions-by-day": {
        isLoading: true,
        failedLoad: false,
        resultset: null,
      },
      "rp-completed": {
        isLoading: true,
        failedLoad: false,
        resultset: null,
      },
      "rp-comp-yoy": {
        isLoading: true,
        failedLoad: false,
        resultset: null,
      },
      "plan-activity-historical": {
        isLoading: true,
        failedLoad: false,
        resultset: null,
      },
    },
    totalSubscriptions: {
      isLoading: true,
      failedLoad: false,
      resultset: null,
    },
    allOrgIds: [
      3,
      2,
      15,
      16,
      4,
      7,
      6,
      10,
      8,
      9,
      19,
      11,
      5,
      12,
      13,
      14,
      20,
      21,
      18,
      22,
      1,
    ],
    error: null,
  },
  globalNotifications: {
    notifications: [],
  },
  form: {
    newPlan: {
      error: {
        imagesError: "Please provide large and small images for this plan.",
      },
      syncError: true,
      syncErrors: {
        plan: {
          draft_name: "Please enter a plan name.",
          draft_lang: "Please choose a plan language.",
          draft_description: "Please enter a plan description.",
          draft_keywords: "Please add at least one keyword.",
          draft_launches_at: "Please add a launch date.",
          draft_categories: "Please add at least one category.",
        },
      },
      registeredFields: [
        {
          name: "plan.draft_lang",
          type: "Field",
        },
        {
          name: "plan.draft_name",
          type: "Field",
        },
        {
          name: "plan.draft_description",
          type: "Field",
        },
        {
          name: "plan.draft_large_image",
          type: "Field",
        },
        {
          name: "plan.draft_small_image",
          type: "Field",
        },
        {
          name: "plan.draft_alternate_organizations",
          type: "Field",
        },
        {
          name: "plan.draft_launches_at",
          type: "Field",
        },
        {
          name: "plan.draft_categories",
          type: "Field",
        },
        {
          name: "plan.draft_keywords",
          type: "Field",
        },
        {
          name: "plan.partner_url",
          type: "Field",
        },
        {
          name: "plan.initial_comment",
          type: "Field",
        },
      ],
    },
  },
};
